name: landing page release
on:
  repository_dispatch:
  push:
    branches:
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn generate

    - name: Deploy to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: endpass.com
        AWS_ACCESS_KEY_ID: ${{ secrets.LANDING_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.LANDING_AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist/'

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      continue-on-error: true
      with:
        type: ${{ job.status }}
        job_name: 'landing page built (release)'
        username: 'GitHub Actions'
        icon_emoji: ':github:'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
